name: Build Check

on:
  push:
    branches: [main, master]
    paths:
      - "1.20.1/**"
      - "1.21.1/**"
      - ".github/workflows/**"
  pull_request:
    branches: [main, master]
    paths:
      - "1.20.1/**"
      - "1.21.1/**"
      - ".github/workflows/**"

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        minecraft_version: ["1.20.1", "1.21.1"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.minecraft_version == '1.20.1' && '17' || '21' }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x ${{ matrix.minecraft_version }}/gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ${{ matrix.minecraft_version }}/.gradle
          key: ${{ runner.os }}-gradle-${{ matrix.minecraft_version }}-${{ hashFiles(format('{0}/**/*.gradle*', matrix.minecraft_version)) }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ matrix.minecraft_version }}-

      - name: Build mod for MC ${{ matrix.minecraft_version }}
        working-directory: ${{ matrix.minecraft_version }}
        run: ./gradlew build

      - name: Upload development artifacts
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: dev-build-mc${{ matrix.minecraft_version }}
          path: ${{ matrix.minecraft_version }}/build/libs/*.jar
          retention-days: 7
